### ISSUE TITLE
怎样体现隐喻、故事

### ISSUE THREAD

**Issue by xiaojingli** [PoemsWithKids/Plans-for-BP#10]
[团队最好的商业计划书是讲故事](http://www.wanhuajing.com/d222337)中举例讲述了故事在BP中的运用。我们要怎样在BP中呈现故事呢？

**Comment by ShuangFarmer** [comment]
- BP主体：家长和孩子
- 故事模型 ：英雄之旅（晓静的灵光一闪）
- 故事大纲 
  孩子和家长，受到诗歌源头的召唤，踏上寻诗之旅，克服困难，最终抵达诗歌源头。
  具体场景，可以是一次游园会，一次踏青，风格温和有趣味，而非竞技类游戏的打打杀杀。  
- 项目痛点
  通过旅途中的小障碍来体现，如刮风下雨，孩子停步不前
- 产品模型
  可通过旅途中偶遇的新朋友，新风景来呈现诗歌卡片。e.g., 在小亭子里偶遇李白叔叔……
  还可以通过使用新道具（e.g., 望远镜）、食物等隐喻，体现产品中包含的长期激励功能。
