### ISSUE TITLE
怎样解决单纯的读诗“形式单一”的问题？

### ISSUE THREAD

**Issue by xiaojingli** [PoemsWithKids/Plans-for-BP#9]
- 主题读诗
- 设计有趣的题目，比如展开自己的想象力作画

**Comment by Linkding** [comment]
参考：”为你读诗“ 公众号
形式：每期邀请一位名人读诗，公众号号同时配上一图精心挑选的画作。

需要思考下，我们产品解决了什么场景的需求？
- 诗——提升词汇能力
- 诗——提升欣赏能力
- 诗——提供了父母睡前的讲故事一种轮换手段？
- 诗——提供给孩子自由阅读的课外之物？
- 诗——孩子读诗，创造诗的渠道？

碎片的想法，没有找到落脚点
